In [4]:
import pandas as pd
data = pd.read_csv('MovieData-2018-2020.csv')
data

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
0,A Quiet Place,PG-13,Drama,2018,"April 6, 2018 (United States)",7.5,456000.0,John Krasinski,Bryan Woods,Emily Blunt,United States,17000000.0,3.503204e+08,Paramount Pictures,90.0
1,Avengers: Infinity War,PG-13,Action,2018,"April 27, 2018 (United States)",8.4,897000.0,Anthony Russo,Christopher Markus,Robert Downey Jr.,United States,321000000.0,2.048360e+09,Marvel Studios,149.0
2,Deadpool 2,R,Action,2018,"May 18, 2018 (United States)",7.7,505000.0,David Leitch,Rhett Reese,Ryan Reynolds,Canada,110000000.0,7.864705e+08,Twentieth Century Fox,119.0
3,Bohemian Rhapsody,PG-13,Biography,2018,"November 2, 2018 (United States)",7.9,476000.0,Bryan Singer,Anthony McCarten,Rami Malek,United Kingdom,52000000.0,9.119026e+08,Twentieth Century Fox,134.0
4,Black Panther,PG-13,Action,2018,"February 16, 2018 (United States)",7.3,661000.0,Ryan Coogler,Ryan Coogler,Chadwick Boseman,United States,200000000.0,1.347598e+09,Marvel Studios,134.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269,Love by Drowning,R,Drama,2020,"November 6, 2020 (United States)",NaN,NaN,Justin Kreinbrink,C.E. Poverman,Nicky Whelan,United States,1000000.0,NaN,Dow Jazz Films,121.0
270,The Robinsons,NaN,Action,2020,"November 10, 2020 (United States)",NaN,NaN,Directors,Aleks Alifirenko Jr.,Billy Hartmann,United States,10000.0,NaN,NaN,90.0
271,More to Life,NaN,Drama,2020,"October 23, 2020 (United States)",3.1,18.0,Joseph Ebanks,Joseph Ebanks,Shannon Bond,United States,7000.0,NaN,NaN,90.0
272,Saving Mbango,NaN,Drama,2020,"April 27, 2020 (Cameroon)",5.7,29.0,Nkanya Nkwai,Lynno Lovert,Onyama Laura,United States,58750.0,NaN,Embi Productions,NaN
273,It's Just Us,NaN,Drama,2020,"October 1, 2020 (United States)",NaN,NaN,James Randall,James Randall,Christina Roz,United States,15000.0,NaN,NaN,120.0

In [9]:
#stratifed data by genre
from sklearn.model_selection import train_test_split

_, stratified_sample = train_test_split(
    data,
    test_size=0.3,
    stratify=data['genre'],
    random_state=1
)

stratified_sample

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
132,Action Point,R,Comedy,2018,"June 1, 2018 (United States)",5.1,11000.0,Tim Kirkby,John Altschuler,Johnny Knoxville,United States,19000000.0,5103663.0,Paramount Pictures,85.0
15,BlacKkKlansman,R,Biography,2018,"August 10, 2018 (United States)",7.5,236000.0,Spike Lee,Charlie Wachtel,John David Washington,United States,15000000.0,93413709.0,Focus Features,135.0
9,Spider-Man: Into the Spider-Verse,PG,Animation,2018,"December 14, 2018 (United States)",8.4,411000.0,Bob Persichetti,Phil Lord,Shameik Moore,United States,90000000.0,375540831.0,Sony Pictures Entertainment (SPE),117.0
210,Captive State,PG-13,Action,2019,"March 15, 2019 (United States)",6.0,51000.0,Rupert Wyatt,Erica Beeney,John Goodman,United States,25000000.0,8808611.0,Participant,109.0
18,Solo: A Star Wars Story,PG-13,Action,2018,"May 25, 2018 (United States)",6.9,306000.0,Ron Howard,Jonathan Kasdan,Alden Ehrenreich,United States,275000000.0,392924807.0,Lucasfilm,135.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,Hotel Artemis,R,Action,2018,"June 8, 2018 (United States)",6.1,49000.0,Drew Pearce,Drew Pearce,Jodie Foster,United Kingdom,15000000.0,13313581.0,The Ink Factory,94.0
57,Bumblebee,PG-13,Action,2018,"December 21, 2018 (United States)",6.7,147000.0,Travis Knight,Christina Hodson,Hailee Steinfeld,China,135000000.0,467989645.0,Hasbro,114.0
243,The Wandering Earth,TV-MA,Action,2019,"February 5, 2019 (China)",6.0,28000.0,Frant Gwo,Gong Geer,Jing Wu,China,48000000.0,699992512.0,Beijing Dengfeng International Culture Communi...,125.0
153,Knives Out,PG-13,Comedy,2019,"November 27, 2019 (United States)",7.9,505000.0,Rian Johnson,Rian Johnson,Daniel Craig,United States,40000000.0,311539397.0,Lionsgate,130.0
261,The Invisible Man,R,Drama,2020,"February 28, 2020 (United States)",7.1,186000.0,Leigh Whannell,Leigh Whannell,Elisabeth Moss,Canada,7000000.0,143151000.0,Universal Pictures,124.0

In [17]:
# Melihat jumlah Data Setiap Gendre
data["genre"].value_counts()

genre
Action       88
Comedy       45
Drama        38
Biography    29
Animation    23
Adventure    19
Horror       15
Crime        12
Fantasy       3
Name: count, dtype: int64

In [15]:
# Mengambil 30 data teratas
sample = stratified_sample.head(30)
sample

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
132,Action Point,R,Comedy,2018,"June 1, 2018 (United States)",5.1,11000.0,Tim Kirkby,John Altschuler,Johnny Knoxville,United States,19000000.0,5103663.0,Paramount Pictures,85.0
15,BlacKkKlansman,R,Biography,2018,"August 10, 2018 (United States)",7.5,236000.0,Spike Lee,Charlie Wachtel,John David Washington,United States,15000000.0,93413709.0,Focus Features,135.0
9,Spider-Man: Into the Spider-Verse,PG,Animation,2018,"December 14, 2018 (United States)",8.4,411000.0,Bob Persichetti,Phil Lord,Shameik Moore,United States,90000000.0,375540831.0,Sony Pictures Entertainment (SPE),117.0
210,Captive State,PG-13,Action,2019,"March 15, 2019 (United States)",6.0,51000.0,Rupert Wyatt,Erica Beeney,John Goodman,United States,25000000.0,8808611.0,Participant,109.0
18,Solo: A Star Wars Story,PG-13,Action,2018,"May 25, 2018 (United States)",6.9,306000.0,Ron Howard,Jonathan Kasdan,Alden Ehrenreich,United States,275000000.0,392924807.0,Lucasfilm,135.0
44,Game Night,R,Action,2018,"February 23, 2018 (United States)",6.9,215000.0,John Francis Daley,Mark Perez,Jason Bateman,United States,37000000.0,117679066.0,Access Entertainment,100.0
144,Once Upon a Time... In Hollywood,R,Comedy,2019,"July 26, 2019 (United States)",7.6,603000.0,Quentin Tarantino,Quentin Tarantino,Leonardo DiCaprio,United States,90000000.0,374565754.0,Columbia Pictures,161.0
103,Brian Banks,PG-13,Biography,2018,"August 9, 2019 (United States)",7.2,5400.0,Tom Shadyac,Doug Atchison,Aldis Hodge,United States,10000000.0,4376819.0,ShivHans Pictures,99.0
64,Upgrade,R,Action,2018,"June 1, 2018 (United States)",7.5,168000.0,Leigh Whannell,Leigh Whannell,Logan Marshall-Green,United States,5000000.0,16706680.0,Goalpost Pictures,100.0
101,Life of the Party,PG-13,Comedy,2018,"May 11, 2018 (United States)",5.6,35000.0,Ben Falcone,Melissa McCarthy,Melissa McCarthy,United States,30000000.0,65859911.0,New Line Cinema,105.0
41,The Nun,R,Horror,2018,"September 7, 2018 (United States)",5.3,127000.0,Corin Hardy,Gary Dauberman,Demián Bichir,United States,22000000.0,365551694.0,Atomic Monster,96.0
225,The Beach Bum,R,Comedy,2019,"March 29, 2019 (United States)",5.5,20000.0,Harmony Korine,Harmony Korine,Matthew McConaughey,Switzerland,5000000.0,4554416.0,Iconoclast,95.0
76,Replicas,PG-13,Drama,2018,"January 11, 2019 (United States)",5.5,34000.0,Jeffrey Nachmanoff,Chad St. John,Keanu Reeves,United Kingdom,30000000.0,9330075.0,Company Films,107.0
264,Dolittle,PG,Adventure,2020,"January 17, 2020 (United States)",5.6,53000.0,Stephen Gaghan,Stephen Gaghan,Robert Downey Jr.,United States,175000000.0,245487753.0,Universal Pictures,101.0
20,Under the Silver Lake,R,Crime,2018,"April 19, 2019 (United States)",6.5,36000.0,David Robert Mitchell,David Robert Mitchell,Andrew Garfield,United States,8500000.0,2053469.0,Vendian Entertainment,139.0
170,Terminator: Dark Fate,R,Action,2019,"November 1, 2019 (United States)",6.2,159000.0,Tim Miller,David S. Goyer,Linda Hamilton,United States,185000000.0,261119292.0,Paramount Pictures,128.0
56,Mary Poppins Returns,PG,Comedy,2018,"December 19, 2018 (United States)",6.7,80000.0,Rob Marshall,P.L. Travers,Emily Blunt,United States,130000000.0,349546142.0,Lucamar Productions,130.0
207,Maleficent: Mistress of Evil,PG,Adventure,2019,"October 18, 2019 (United States)",6.6,91000.0,Joachim Rønning,Linda Woolverton,Angelina Jolie,United States,185000000.0,491730089.0,Walt Disney Pictures,119.0
250,The Prodigy,R,Fantasy,2019,"February 8, 2019 (United States)",5.9,24000.0,Nicholas McCarthy,Jeff Buhler,Taylor Schilling,United States,6000000.0,21150265.0,Orion Pictures,92.0
10,Mission: Impossible - Fallout,PG-13,Action,2018,"July 27, 2018 (United States)",7.7,303000.0,Christopher McQuarrie,Bruce Geller,Tom Cruise,United States,178000000.0,791657398.0,Paramount Pictures,147.0
96,Overboard,PG-13,Comedy,2018,"May 4, 2018 (United States)",6.0,36000.0,Rob Greenberg,Bob Fisher,Eugenio Derbez,United States,12000000.0,91244913.0,Metro-Goldwyn-Mayer (MGM),112.0
97,Arctic,PG-13,Adventure,2018,"January 31, 2019 (Denmark)",6.8,46000.0,Joe Penna,Joe Penna,Mads Mikkelsen,Iceland,2000000.0,4165776.0,Armory Films,98.0
126,Uncle Drew,PG-13,Comedy,2018,"June 29, 2018 (United States)",5.8,13000.0,Charles Stone III,Jay Longino,Kyrie Irving,United States,19000000.0,46664414.0,Summit Entertainment,103.0
152,John Wick: Chapter 3 - Parabellum,R,Action,2019,"May 17, 2019 (United States)",7.4,296000.0,Chad Stahelski,Derek Kolstad,Keanu Reeves,United States,75000000.0,327281779.0,Lionsgate,130.0
176,The Best of Enemies,PG-13,Biography,2019,"April 5, 2019 (United States)",7.2,13000.0,Robin Bissell,Robin Bissell,Taraji P. Henson,United States,10000000.0,10209813.0,Astute Films,133.0
124,Hell Fest,R,Horror,2018,"September 28, 2018 (United States)",5.5,15000.0,Gregory Plotkin,Seth M. Sherwood,Cynthea Mercado,United States,5500000.0,18160930.0,CBS Films,89.0
14,Ant-Man and the Wasp,PG-13,Action,2018,"July 6, 2018 (United States)",7.0,333000.0,Peyton Reed,Chris McKenna,Paul Rudd,United States,162000000.0,622674139.0,Marvel Studios,118.0
47,Bad Times at the El Royale,R,Crime,2018,"October 12, 2018 (United States)",7.1,135000.0,Drew Goddard,Drew Goddard,Jeff Bridges,United States,32000000.0,31882724.0,Goddard Textiles,141.0
42,The Equalizer 2,R,Action,2018,"July 20, 2018 (United States)",6.7,141000.0,Antoine Fuqua,Richard Wenk,Denzel Washington,United States,62000000.0,190400157.0,Columbia Pictures,121.0
171,Downton Abbey,PG,Drama,2019,"September 20, 2019 (United States)",7.4,43000.0,Michael Engler,Julian Fellowes,Stephen Campbell Moore,United Kingdom,13000000.0,237860050.0,Carnival Film & Television,122.0

In [20]:
# Menghitung Rata-Rata dan Standar Deviasi
print("Rata-rata Budget :", sample['budget'].mean())
print("Standar Deviasi :", sample['budget'].std())

Rata-rata Budget : 63766666.666666664
Standar Deviasi : 74316626.13130544

MENGHITUNG ESTIMASI

In [21]:
import scipy.stats as stats
import math

# Specify sample mean (x_bar), sample standard deviation (s),
# sample size (n) and confidence level

x_bar = 63.66
s = 74.13
n = 30
confidence_level = 0.95

# Calculate alpha, degrees of freedom (df),
# the critical t-value, and the margin of error

alpha = (1 - confidence_level)
df = n - 1
standard_error = s / math.sqrt(n)

critical_t = stats.t.ppf(1 - alpha/2, df)
margin_of_error = critical_t * standard_error

# Calculate the lower and upper bound

lower_bound = x_bar - margin_of_error
upper_bound = x_bar + margin_of_error

# Print the results

print("Critical t-value: {:.3f}".format(critical_t))
print("Margin of Error: {:.3f}".format(margin_of_error))
print("Confidence Interval: [{:.3f}, {:.3f}]".format(lower_bound, upper_bound))
print("The {:.1%} confidence interval for the population mean is:".format(confidence_level))
print("between {:.3f} and {:.3f}".format(lower_bound, upper_bound))

Critical t-value: 2.045
Margin of Error: 27.681
Confidence Interval: [35.979, 91.341]
The 95.0% confidence interval for the population mean is:
between 35.979 and 91.341